// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsCopilot.SafeActions.Infrastructure.Persistence;

#nullable disable

namespace OpsCopilot.SafeActions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SafeActionsDbContext))]
    partial class SafeActionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("safeActions")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpsCopilot.SafeActions.Domain.Entities.ActionRecord", b =>
                {
                    b.Property<Guid>("ActionRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExecutedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExecutionPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualRollbackGuidance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutcomeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollbackOutcomeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollbackPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollbackStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("RolledBackAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ActionRecordId");

                    b.HasIndex("RunId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ActionRecords", "safeActions");
                });

            modelBuilder.Entity("OpsCopilot.SafeActions.Domain.Entities.ApprovalRecord", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApproverIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ActionRecordId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ApprovalRecords", "safeActions");
                });

            modelBuilder.Entity("OpsCopilot.SafeActions.Domain.Entities.ExecutionLog", b =>
                {
                    b.Property<Guid>("ExecutionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ExecutionLogId");

                    b.HasIndex("ActionRecordId");

                    b.HasIndex("ExecutedAtUtc");

                    b.ToTable("ExecutionLogs", "safeActions");
                });
#pragma warning restore 612, 618
        }
    }
}
